title: "BiSID-5k: A Bimodal Dataset for Seed Classification from Visible and Near-Infrared Imaging"
description: "Maksim Kukushkin, Martin Bogdan, Simon Goertz, Jan-Ole Callsen, Eric Oldenburg, Matthias Enders, and Thomas Schmid"
email: kukushkin@informatik.uni-leipzig.de
theme: jekyll-theme-cayman
show_downloads: true